name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            configure_preset: linux-gcc-release-glfw
            build_preset: linux-gcc-release-glfw
            artifact_name: sleep-blocker-linux-glfw

          - os: ubuntu-latest
            configure_preset: linux-gcc-release-sdl
            build_preset: linux-gcc-release-sdl
            artifact_name: sleep-blocker-linux-sdl

          - os: windows-latest
            configure_preset: windows-msvc-release-glfw
            build_preset: windows-msvc-release-glfw
            artifact_name: sleep-blocker-windows-glfw.exe

          - os: windows-latest
            configure_preset: windows-msvc-release-sdl
            build_preset: windows-msvc-release-sdl
            artifact_name: sleep-blocker-windows-sdl.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
              libx11-dev \
              libxrandr-dev \
              libxinerama-dev \
              libxcursor-dev \
              libxi-dev \
              libxext-dev \
              libwayland-dev \
              wayland-protocols \
              libxkbcommon-dev \
              libgl1-mesa-dev \
              libglu1-mesa-dev \
              libegl1-mesa-dev \
              libsystemd-dev

      - name: Configure
        run: cmake --preset ${{ matrix.configure_preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.build_preset }}

      - name: Rename binary
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            cp build/${{ matrix.configure_preset }}/Release/sleep-blocker.exe ${{ matrix.artifact_name }}
          else
            cp build/${{ matrix.configure_preset }}/sleep-blocker ${{ matrix.artifact_name }}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sleep-blocker-linux-glfw
            sleep-blocker-linux-sdl
            sleep-blocker-windows-glfw.exe
            sleep-blocker-windows-sdl.exe
